### ISSUE TITLE
dlib video face detection takes massive amount of time

### ISSUE THREAD

**Issue by abduct** [shaoanlu/faceswap-GAN#1]
I am not a jupyter user although I assume I have the repository setup correctly as it seems to be doing work. I have been working with other code bases for a while using the same modules so a dependency issue is likely not an issue.

When I step through the code for dlib_video_face_detection.ipynb I get to the code block where moviepy does some manipulation of an input video. According to the timestamp on the output I am looking at a very long time before it is complete.

`0%|                                                                           | 9/15887 [11:09<329:34:28, 74.72s/it]`

The target video is 1280x720, 00:08:50 long with a data rate of 1413kbps. My hardware consists of a 3.5ghz i5, gtx1080, and 16gb of ram. Training large data sets have not been a problem for me so I am unsure of why processing a video frame by frame would take this long.

What is the purpose of the 

```
output = '_.mp4'
clip1 = VideoFileClip("x-cropped.mp4")
clip = clip1.fl_image(process_video)#.subclip(0,10) #NOTE: this function expects color images!!
%time clip.write_videofile(output, audio=False)
```

block besides to run the process_video method on each frame? I have used the dlib module as a stand alone script and it processes the video in a handful of minutes pulling many faces as a result.

Would it be beneficial to pre-process the video file in ffmpeg before handing the work to the notebook in any way? Perhaps rip the frames beforehand so that moviepy would not need to step frame by frame?

**Comment by shaoanlu** [comment]
I just ran an experiment for 1280x720 video on K80 GPU. Got ~3 iters per sec..
Its weird to see such slow speed on GTX1080. Did face_recognition use GPU for acceleration on cnn model?

**Comment by abduct** [comment]
Is there an output which would tell me if face_recognition used the GPU or not? I don't think I got any output from the code blocks besides when one of them downloaded ffmpeg (which was installed previously weirdly enough) and when the progress bar appeared.

I am going to attempt to convert the notebook into a script via `jupyter nbconvert --execute` and see if I can debug it a bit easier. I am a novice with jupyter and frankly I kinda dislike it's work flow.

**Comment by visualmemories** [comment]
It's very likely your GPU isn't being detected. See #8

**Comment by futurexiong** [comment]
I met the same issue. GPU detected, and tensorflow-gpu works well, but seems that dlib does not use GPU.

**Comment by petergerten** [comment]
I built dlib from source - after that GPU support worked for me

**Comment by futurexiong** [comment]
@petergerten After searching some material, I just wanted to do what you mentioned. I want to recompile dlib,but I am not familiar  with C/C++ compiling. Can you please give me some instructions here?Thanks.

**Comment by petergerten** [comment]
@futurexiong it is really just
```
git clone https://github.com/davisking/dlib.git
cd dlib
python setup.py install

```
assuming you have all dependencies installed.

**Comment by futurexiong** [comment]
@petergerten Still not working. Do I need '--yes DLIB_USE_CUDA' compile option?

**Comment by futurexiong** [comment]
Dlib compile log shows me not installing cuDNN.

**Comment by futurexiong** [comment]
Hi, @petergerten , I installed all cuDNN deb dependencies and built dlib with cuda enabled successfully. But when I run dlib_video_face_detection.ipynb again, it still used CPU not GPU, which about 16s/iterate, that is too slow.Any ideas?

**Comment by futurexiong** [comment]
@abduct how did you solve this problem?

**Comment by futurexiong** [comment]
After making some efforts, I not only install cuDNN through .deb file but also install it through tar file, finally face_recognition works with gpu, now it's about 5-9 it/s.

But when I recompile dlib, it show some logs as follow:

`CMake Warning at /home/futurexiong/dlib-19.9.0/dlib/external/pybind11/tools/pybind11Tools.cmake:131 (add_library):
  Cannot generate a safe runtime search path for target dlib_python because
  files in some directories may conflict with libraries in implicit
  directories:
    runtime library [libcudnn.so.6] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /usr/local/cuda/lib64
  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:96 (pybind11_add_module)
`
I don't know why and what it will affect, maybe I don't need to install cuDNN through .deb file?

Env: Ubuntu14.04, CUDA 8.0, cuDNN 6.0 for CUDA8.0.
