### ISSUE TITLE
SOS, I don't have the weights files!

### ISSUE THREAD

**Issue by Elephantameler** [shaoanlu/faceswap-GAN#102]
try:
	encoder.load_weights("models/encoder.h5")
	decoder_A.load_weights("models/decoder_A.h5")
	decoder_B.load_weights("models/decoder_B.h5")
	# netDA.load_weights("models/netDA.h5") 
	# netDB.load_weights("models/netDB.h5") 
	print("model loaded.")
except:
	print("weights file not found.")
	pass

Failed loading. Something goes wrong with weights files.
-------------------------------------------------------------------
I ran the  FaceSwap_GAN_v2.1_train at the beginning, and threw this exception.
So where can I find the all weight files, or I need to run which file first?

**Comment by Elephantameler** [comment]
Can you give us an usage ? Thank you very much.

**Comment by jlllweco** [comment]
> try:
> encoder.load_weights("models/encoder.h5")
> decoder_A.load_weights("models/decoder_A.h5")
> decoder_B.load_weights("models/decoder_B.h5")
> # netDA.load_weights("models/netDA.h5")
> # netDB.load_weights("models/netDB.h5")
> print("model loaded.")
> except:
> print("weights file not found.")
> pass
> 
> ## Failed loading. Something goes wrong with weights files.
> I ran the FaceSwap_GAN_v2.1_train at the beginning, and threw this exception.
> So where can I find the all weight files, or I need to run which file first?

May I ask where can I download the model weights file? I haven't found it.
