### ISSUE TITLE
Can you tell me the version of keras and tensorflow you are using?

### ISSUE THREAD

**Issue by kaloronahuang** [shaoanlu/faceswap-GAN#104]
I have been configurating these for a couple of days, finding a usable solution. It seems that there are troubles caused by inappropriate version. Thanks for your great work.

**Comment by shaoanlu** [comment]
I've updated the requirements in readme. All the notebooks are runnable on google colab.

**Comment by kaloronahuang** [comment]
Thanks for the details!
