### ISSUE TITLE
Face alignment not work if that the video "is_higher_than_1080p" 

### ISSUE THREAD

**Issue by kazhnb** [shaoanlu/faceswap-GAN#106]
Hi,
FaceSwap_GAN_v2.2 is pretty good 
but when the video resolution is_higher_than_1080p and others
face alignment looks not work .

I've checked and found the reason could be the [get_faces_bbox] method
 does not downscale the pnts result , so the landmarks is not correct for face alignment .

**Comment by shaoanlu** [comment]
Thanks for pointing out the issue. I just fixed the bug. The face alignment should work on large input resolutions now.
