### ISSUE TITLE
ValueError: cannot reshape array of size 331776 into shape (4,3,3,64,64,3)

### ISSUE THREAD

**Issue by cscyangj** [shaoanlu/faceswap-GAN#111]
figure = figure.reshape((4,batchSize//2) + figure.shape[1:])
ValueError: cannot reshape array of size 331776 into shape (4,3,3,64,64,3)

Seems same as https://github.com/dfaker/df/pull/29.

**Comment by shaoanlu** [comment]
Batch size is supposed to be an even number.
