### ISSUE TITLE
gtx 1060 with 6G ram, out of memory

### ISSUE THREAD

**Issue by chikiuso** [shaoanlu/faceswap-GAN#13]
I am running the script in gtx 1060 with 6G ram laptop, it halts on 56 niters and said out of memory, is there any way I could lower the memory requirement? Thanks.

**Comment by shaoanlu** [comment]
You can 
1. Reduce batch size.
2. Reduce the dense layer dimension from 1024 to 512.
3. Remove residual blocks in the decoder.

**Comment by chikiuso** [comment]
Hi Shaoanlu,
  About (1), is it batchSize=8?
  About (2), is it     x = Dense(1024)(Flatten()(x)) and x = Dense(4*4*1024)(x)?

Thanks!

**Comment by shaoanlu** [comment]
Yes.

**Comment by chikiuso** [comment]
Thanks for your help Shaoanlu, but I am not lucky enough as it consume 5.9G ram out of 6G once I started the training.

**Comment by chikiuso** [comment]
May I ask how many Gb of graphic card ram do you have? thanks.

**Comment by shaoanlu** [comment]
I used Tesla K80 for training, which provides 12GB vRAM.
