### ISSUE TITLE
ValueError: Object arrays cannot be loaded when allow_pickle=False

### ISSUE THREAD

**Issue by ak9250** [shaoanlu/faceswap-GAN#133]
getting this error in colab notebook after running 
fd = MTCNNFaceDetector(sess=K.get_session(), model_path="./mtcnn_weights/")

**Comment by evanxephon** [comment]
Encounter the same problem. 
You may add a parameter in Network.load() function in mtcnn_detect_face.py.
like 'data_dict = np.load(data_path, **allow_pickle=True**,  encoding='latin1').item()' in line 87.
Restart the notebook.
Remove the old file and upload your own one before import MTCNNFaceDetector .
`%cd "faceswap-GAN"
!rm mtcnn_detect_face.py
from google.colab import files
files.upload()`
It works for me.

**Comment by ak9250** [comment]
@evanxephon thanks that worked although I think its easier to do %%writefile mtcnn_detect_face.py and change that file in the cell after getting the source and target videos

**Comment by ybugroup** [comment]
I am still getting this error on Google Colab.  Can someone please update?  Thanks in advance!

https://colab.research.google.com/github/shaoanlu/faceswap-GAN/blob/master/colab_demo/faceswap-GAN_colab_demo.ipynb
