### ISSUE TITLE
ImportError: No module named 'keras_vggface'

### ISSUE THREAD

**Issue by bigsea00001** [shaoanlu/faceswap-GAN#14]
Thank you for developing a great program. I installed keras_vggface as "!Pip install keras_vggface" normally. But, the following error occurred. I searched the problem on Google but could not resolve it. Could you tell me how to fix it? Thank you in advance.
===================================

IN [1]: from keras_vggface.vggface import VGGFace
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-229bb387e346> in <module>()
----> 1 from keras_vggface.vggface import VGGFace

ImportError: No module named 'keras_vggface'

**Comment by claesjanwolff** [comment]
Same issue here. What is the solution?

**Comment by J0S3dj3** [comment]
the same thing happens to me in visual studio code open from anaconda
