### ISSUE TITLE
dataset for training

### ISSUE THREAD

**Issue by kalyo-zjl** [shaoanlu/faceswap-GAN#19]
Hi, @shaoanlu 

Thanks for your nice work!

you have shown a result of trained models transforming Hinako Sano (佐野ひなこ, left) to Emi Takei (武井咲, right). Since you have provided the source video of Hinako Sano (佐野ひなこ, left), the training data of Emi Takei (武井咲, right) is not provided. Could please kindly give a link to this data.

Thanks.

**Comment by shaoanlu** [comment]
由於deepfakes的特殊性以及日本對肖像權、隱私權的保護，我認為分享過多關於訓練資料的訊息並不妥當，抱歉。只能說訓練資料的影片都是從youtube上搜尋到的。

**Comment by jlllweco** [comment]
Would you please kindly share the video and dataset with me? It's really hard to find great dataset.
Thank you so much!
