### ISSUE TITLE
How can I find definition for nc_D_inp?

### ISSUE THREAD

**Issue by gufengwyx8** [shaoanlu/faceswap-GAN#2]
[https://github.com/shaoanlu/faceswap-GAN/blob/master/FaceSwap_GAN_github.ipynb](url)
netDA = Discriminator(nc_D_inp)
netDB = Discriminator(nc_D_inp)

**Comment by shaoanlu** [comment]
It is 3. I accidentally deleted that line in config, thanks for the feedback.
