### ISSUE TITLE
Training stops at a certain iteration

### ISSUE THREAD

**Issue by zoulock** [shaoanlu/faceswap-GAN#22]
I have a GTX 1080 and have trained successfully the original NN, but when I try to train these, they run for like an hour and then stop training at a given iteration. If I rerun the function, it stops at the same one.

**Comment by zoulock** [comment]
Also there is no output in the terminal.

**Comment by zoulock** [comment]
I'm running the v2, in linux with 16GB of memory.

**Comment by shaoanlu** [comment]
1. In 10. Star training:
```python
while gen_iterations < 20000: # change 20000 to max iteration you want
```
2. The intermediate results are shown in the cell of jupyter notebook during training.

**Comment by zoulock** [comment]
Thank you. I thought it would stop once it finished the epochs.
