### ISSUE TITLE
Could you change the input and output to 128, 128 for WGAN model?

### ISSUE THREAD

**Issue by chikiuso** [shaoanlu/faceswap-GAN#25]
Hi, I see a WGAN in temp folder.  Could you help change the input and output to 128, 128 for WGAN model? I tried to change it but not succeed, Thanks!!

**Comment by chikiuso** [comment]
I tried adding a conv2d(32) on generator and discriminator , but it shows this error :  

ValueError: setting an array element with a sequence.

**Comment by chikiuso** [comment]
I keep testing different dataset sets and found that WGAN produces the most stable results.

**Comment by shaoanlu** [comment]
Interesting, what do you mean by stable?

To increase input resolution, you have to modify codes in at least four places:
1. In `def __init__(...)`, set `self.img_size = 128`
2. In `def Encoder(...)`, add one more `conv_block(x, 1024)` before `Dense(1024)`.
3. In `def Decoder_ps(...)`, add one more `upscale_ps(64)(x)` before `resblock`.
4. In `def read_image(...)`, use `warped_img, target_img = random_warp128(image)`.
(Optional) 5. Add one more `conv_block_d()` in `def Discriminator(...)`

**Comment by chikiuso** [comment]
Great! Thanks!!
