### ISSUE TITLE
"Weights file not found." despite them being present

### ISSUE THREAD

**Issue by Irastris** [shaoanlu/faceswap-GAN#29]
```py
try:
	encoder.load_weights("models/encoder.h5")
	decoder_A.load_weights("models/decoder_A.h5")
	decoder_B.load_weights("models/decoder_B.h5")
	# netDA.load_weights("models/netDA.h5") 
	# netDB.load_weights("models/netDB.h5") 
	print("model loaded.")
except:
	print("weights file not found.")
	pass
```
At this point in the code, it always fails, saying it couldn't find the weight files. They are located at `./faceswap-GAN-master/models/`. Is this incorrect? I should note that the model is the Trump to Cage model from the [deepfakes/faceswap](https://github.com/deepfakes/faceswap) project, and that I commented out netDA and netDB because they do not exist.

Any help? Thank you.

**Comment by Irastris** [comment]
Apologies, I figured out where I was going wrong.

**Comment by shaoanlu** [comment]
Never mind. I'll modify the error message to prevent confusing.

**Comment by futurexiong** [comment]
@Irastris @shaoanlu  Means I should run 1 ~ 10 for model folder generation?

**Comment by futurexiong** [comment]
@Irastris @shaoanlu where can I get the models folder?

**Comment by vamzii** [comment]
![screenshot 2](https://user-images.githubusercontent.com/35881602/36815586-1c378bc4-1cd3-11e8-981d-716663547516.png)
![screenshot 3](https://user-images.githubusercontent.com/35881602/36815587-1c851236-1cd3-11e8-8696-5b1d330ef08a.png)
![screenshot 4](https://user-images.githubusercontent.com/35881602/36815588-1cc0fe36-1cd3-11e8-831b-e503fbbe3f97.png)
![screenshot 5](https://user-images.githubusercontent.com/35881602/36815590-1cfba9aa-1cd3-11e8-9bce-f342d304bba0.png)
![screenshot 1](https://user-images.githubusercontent.com/35881602/36815591-1d342208-1cd3-11e8-8432-1231efc47efe.png)

"Error occurs during loading weights files."

i placed the training files too, then too getting this error, any help?

**Comment by shaoanlu** [comment]
@vamzii It seems like you use the wrong model. Where are those weights files come from?

**Comment by vamzii** [comment]
i copied the model files from fakeapp 1.1,where should i get the actual models from mate??

**Comment by jlllweco** [comment]
I got the same error 
![image](https://user-images.githubusercontent.com/36145675/51011494-bd312080-1593-11e9-994c-7ff13f210af0.png)
How should I arrange the file path?
I download the file from https://anonfile.com/p7w3m0d5be/face-swap.zip
![image](https://user-images.githubusercontent.com/36145675/51011662-56603700-1594-11e9-9d7e-d7e54701121e.png)
and then I arrange the file path like this:
![image](https://user-images.githubusercontent.com/36145675/51011731-98897880-1594-11e9-8e8f-77862a7e1401.png)
May I ask how can I fix it? Is there anything wrong with the model?

**Comment by jlllweco** [comment]
> ```python
> try:
> 	encoder.load_weights("models/encoder.h5")
> 	decoder_A.load_weights("models/decoder_A.h5")
> 	decoder_B.load_weights("models/decoder_B.h5")
> 	# netDA.load_weights("models/netDA.h5") 
> 	# netDB.load_weights("models/netDB.h5") 
> 	print("model loaded.")
> except:
> 	print("weights file not found.")
> 	pass
> ```
> 
> At this point in the code, it always fails, saying it couldn't find the weight files. They are located at `./faceswap-GAN-master/models/`. Is this incorrect? I should note that the model is the Trump to Cage model from the [deepfakes/faceswap](https://github.com/deepfakes/faceswap) project, and that I commented out netDA and netDB because they do not exist.
> 
> Any help? Thank you.

Would you please tell me what's wrong with it?

**Comment by shaoanlu** [comment]
faceswap-GAN model weights files are not compatible with deepfakes'.

**Comment by jlllweco** [comment]
> faceswap-GAN model weights files are not compatible with deepfakes'.

Oh! Thank you so much for your help! May I ask where can I get the model weights file? Thank you so much for helping beginners. 
By the way,  is there any great dataset? I try to input video by myself. The result is really bad and I only get this in raw-image:
![image](https://user-images.githubusercontent.com/36145675/51024061-7fe48700-15c3-11e9-8380-22d1c809ad94.png)

Here is the aligned image
![image](https://user-images.githubusercontent.com/36145675/51024174-bb7f5100-15c3-11e9-9a54-7f7a7d37e745.png)

**Comment by jlllweco** [comment]
> ```python
> try:
> 	encoder.load_weights("models/encoder.h5")
> 	decoder_A.load_weights("models/decoder_A.h5")
> 	decoder_B.load_weights("models/decoder_B.h5")
> 	# netDA.load_weights("models/netDA.h5") 
> 	# netDB.load_weights("models/netDB.h5") 
> 	print("model loaded.")
> except:
> 	print("weights file not found.")
> 	pass
> ```
> 
> At this point in the code, it always fails, saying it couldn't find the weight files. They are located at `./faceswap-GAN-master/models/`. Is this incorrect? I should note that the model is the Trump to Cage model from the [deepfakes/faceswap](https://github.com/deepfakes/faceswap) project, and that I commented out netDA and netDB because they do not exist.
> 
> Any help? Thank you.

May I ask where can I download model weights? Thank you so much for your help.
