### ISSUE TITLE
Idea about matching color before/during training.

### ISSUE THREAD

**Issue by room3dev** [shaoanlu/faceswap-GAN#30]
I found that one factor for archive good result depends on the variety of lighting/color the data set but sometimes we have a very limit dataset. 
Is it possible to match color between two pictures before/during to improve the result of training?
http://answers.opencv.org/question/178127/matching-colors-between-two-pictures-in-opencv/

**Comment by shaoanlu** [comment]
You can add any image preprocessing you want in section 9 function `read_image()`. Or un-comment the  `random_channel_shift()`function in `imageaugmentation.py`.
