### ISSUE TITLE
Swapping mouth movement

### ISSUE THREAD

**Issue by rosenb0rg** [shaoanlu/faceswap-GAN#35]
Does anyone have any idea how one would approach swapping mouth movement? I.e. transforming the target's mouth shape to match the source, rather than swapping the look. This may be a different project entirely...

**Comment by shaoanlu** [comment]
Have a look at [pix2pix approach](https://towardsdatascience.com/face2face-a-pix2pix-demo-that-mimics-the-facial-expression-of-the-german-chancellor-b6771d65bf66) and [Face2Face](https://www.youtube.com/watch?v=ohmajJTcpNk).
