### ISSUE TITLE
Feather edge of Smoothed bbox

### ISSUE THREAD

**Issue by ccsv** [shaoanlu/faceswap-GAN#39]
I want to suggest adding an algorithm to feather the edges of the bounding box such as the opencv feather blender or use a opacity gradient to blend in the bounding box edges where an radius is defined. This would hide the jitter a bit better.

**Comment by shaoanlu** [comment]
There is already a alpha blending introduced in `process_video()`, which looks like:
```python
image[x0+h//15:x1-h//15, y0+w//15:y1-w//15,:] = mask/255*result + (1-mask/255)*roi_image_rgb
```
where `image` is the input frame image, `mask` is the alpha mask w/ blurred edges `result` is the face generated by the model, and `roi_image_rgb` is the face bbox region of `image`.

Also, I've experimented with poisson blending but it aggravated the jitter.

What is the difference between feather blending with alpha blending? Do you mean that we should apply blending not only on video making but also training?
