### ISSUE TITLE
Have you implemented something like this for the alignment and smoothing?

### ISSUE THREAD

**Issue by Nelthirion** [shaoanlu/faceswap-GAN#4]
Here's the [Link](https://matthewearl.github.io/2015/07/28/switching-eds-with-python/)... Do you think this approach does better with the alignments or the current code is better ?

**Comment by shaoanlu** [comment]
It is likely to perform better alignment when the face landmarks are correctly detected. For now I'm more interested in designing a good architecture of the neural network. I'll go back to alignment and smoothing after I make enough progress.

Thanks for the information.

**Comment by Nelthirion** [comment]
You're welcome... by the way, I tried implementing the [main paper about unsupervised image 2 image translation](https://github.com/mingyuliutw/UNIT) in Keras and ended up having horrible artifacts... Here's another [link](https://github.com/zsdonghao/Unsup-Im2Im) to this approach...

Maybe you could do it better than my mess!

Keep up the good work...

**Comment by shaoanlu** [comment]
Cool! Wonder you would like to share the result or do you have any idea why it produces artifact?

**Comment by Nelthirion** [comment]
I think it's mainly because I suck at implementing a proper Keras model. Here's the [code](https://gist.github.com/Nelthirion/603f5aa3fb4b0f6eb06421fc172325c2) if you're interested... 

I'd be glad if you could point where I was going wrong with the code...
