### ISSUE TITLE
Video generation runs out of GPU

### ISSUE THREAD

**Issue by tensor8** [shaoanlu/faceswap-GAN#41]
Using 2x K80s. Training works fine, but video generation always runs out of GPU memory, even with batch size 1.

Any way to fix this?

**Comment by chikiuso** [comment]
Video generation takes much RAM, you could try a lower input video .mp4 such as 480 width.

**Comment by tensor8** [comment]
Thanks. 480 still runs out though... Is it worth compiling dlib without GPU?

**Comment by gradient-descent-into-madness** [comment]
This has also been an issue for me. One comment in process_video() suggests resizing each frame before using the `face_recognition` cnn model (which I understand consume a lot of memory):

input_img = cv2.resize(input_img, (input_img.shape[1] // 2, input_img.shape[0] // 2))

As for myself, I set a global variable called `scale_factor`, which I decrease gradually on each memory exception
    
`small_img = cv2.resize(input_img, (int(input_img.shape[1]*scale_factor), int(input_img.shape[0]*scale_factor)))`

I run `small_img` through face recognition and scale up the results to match the original video resolution:

```
for (x0, y1, x1, y0) in faces:
        x0 = int(x0 / scale_factor)
        x1 = int(x1 / scale_factor)
        y0 = int(y0 / scale_factor)
        y1 = int(y1 / scale_factor)
```
It's not perfect and may introduce some jitter, so I'm curious what others may have to say. Another approach is to use the `face_recognition` and GAN models separately, so they aren't both consuming memory: for each frame, save out original faces and their positions in the frame. Then, load the GAN model, iterate over the frames again and swap the faces. I was considering implementing this mult-pass approach and maybe also applying a superresolution model trained on the target to fill in the details and achieve faces > 128x128.
