### ISSUE TITLE
dlib_video_face_detection extract 2 different sizes?

### ISSUE THREAD

**Issue by ZeroCool22** [shaoanlu/faceswap-GAN#44]
**186x186** & **223x222**

![screenshot_9](https://user-images.githubusercontent.com/13344308/36059727-3446e180-0e1c-11e8-956d-bf235d9f6072.png)

It's ok or it's a bug?

**Comment by shaoanlu** [comment]
It's intended to left the output resolution as it is. Images are resized to 256x256 during data loading/pre-processing of training process.

The current dlib_video_face_detection notebook extract faces at 30fps (this may varies depending on input fps). I think its better to reduce it to 3 ~ 5 fps so there will be little duplicate images. I will update the script later.

**Comment by ZeroCool22** [comment]
Thx.
