### ISSUE TITLE
FaceSwap_GAN_v2_test_video_MTCNN "NameError: name 'os' is not defined"

### ISSUE THREAD

**Issue by ZeroCool22** [shaoanlu/faceswap-GAN#56]
![screenshot_1](https://user-images.githubusercontent.com/13344308/36169285-9d315f20-10da-11e8-9ba4-35d45db274cd.png)

**Comment by ZeroCool22** [comment]
@shaoanlu Can you tell me please how solve it? Thx.

**Comment by kimphysics** [comment]
simple "import os" will solve the error

**Comment by ZeroCool22** [comment]
@kimphysics Where i should add that? Sorry, i have zero programming skills.

**Comment by shaoanlu** [comment]
Fixed.

**Comment by ZeroCool22** [comment]
@shaoanlu Thx!
