### ISSUE TITLE
Is it possible to enable multi GPU support?

### ISSUE THREAD

**Issue by leftler** [shaoanlu/faceswap-GAN#61]
I have access to a machine that has two K60 Tesla cards attached to it. Running FaceSwap_GAN_v2_train.ipynb I can see in `nvidia-smi` that one GPU was at 100% usage and one was at 0% usage.

Is there any configuration I need to do to allow the libraries that your script calls to use more than one GPU?

**Comment by shaoanlu** [comment]
Keras supports multi-GPU. Please refer to its [documentation](https://keras.io/utils/#multi_gpu_model) for more information.

**Comment by leftler** [comment]
Thanks! I will read up on the Keras documentation, I just needed to know where to start looking.

**Comment by RaineyWu** [comment]
> Keras supports multi-GPU. Please refer to its [documentation](https://keras.io/utils/#multi_gpu_model) for more information.

i try to use the multi_gpu_model but there is a model layer name conflict happened. how should i use it properly? thanks for reply！

**Comment by RaineyWu** [comment]
> Thanks! I will read up on the Keras documentation, I just needed to know where to start looking.

does your multi gpu model work out?

**Comment by RaineyWu** [comment]
> Keras supports multi-GPU. Please refer to its [documentation](https://keras.io/utils/#multi_gpu_model) for more information.
And  i tried, multi_gpu_model did not surport GANs model? do you have any thought about it?
