### ISSUE TITLE
"Weights file not found."

### ISSUE THREAD

**Issue by EmDash1** [shaoanlu/faceswap-GAN#63]
Hello,

Trying to get this to work - it doesn't seem to find the model files inside the /models/ folder, nor does it seem to create it.
I've even attempted to paste in model files from other places, but to no avail. What am I doing wrong?
Getting "Weights file not found."
Is there any other script I need to run before the training notebook?
Everything seems to work normally, all of the dependencies are installed correctly. Any help would be much appreciated!

Thanks!

**Comment by shaoanlu** [comment]
Which notebook did you use?

**Comment by EmDash1** [comment]
I have tried the FaceSwap_GAN_github.ipynb as well as the V2_train and the V2_sz128. Same problem everywhere.
Banally, the actual error I get is 'No such file or directory' -- am I supposed to create the model files by running something else first?
If I manually create empty files (models/encoder.h5 etc.), I get a "Unable to open file (file signature not found)" error.
I'm sorry if I'm missing something obvious.

**Comment by shaoanlu** [comment]
The weights files will be saved to ./models folder once 300 iters during training. So if you haven’t trained any model before,  be empty.
