### ISSUE TITLE
IDEA how to recognize face behind obstacles in image sequence.

### ISSUE THREAD

**Issue by iperov** [shaoanlu/faceswap-GAN#65]
sry bad english, but I will try to explain.

1) extract faces from regular extractor, such as 'face_alignment' or 'face_recognition'
2) now we got images with face landmarks for every image for one face,
 and some images where face was not recognized behind obstacles
3) make new CNN , and train it for 68 pieces of face (for example 8x8pix per piece) for 68 (x,y) targets across:
  variant a) all images
  variant b) +- 5 images from image where face not recognized
4) now in theory CNN must recognize partial face landmarks in images where face was not recognized.
5) now we got landmark positions, and more than half of them will be wrong.
6) then try to reconstruct 68 landmarks by every 3 in a row. = (68-3)+1 variations.
7) combine together most nearest variations and get one average of them
8) now we got face behind obstacle and can train it with GAN masks :D

so what you thinking ? Im beginner of NN's and cannot implement it right now.

**Comment by shaoanlu** [comment]
I think the easiest way to get supervised mask label is to train NNs for segmentation. There are many dataset available, for example, LFW face dataset. For me, I want to keep the learning unsupervised. I simply do not have enough resouces and lack of motivation on building additional models and spending time training them.

**Comment by petergerten** [comment]
@iperov regarding @shaoanlu 's suggestion: this seems to be promising: https://github.com/YuvalNirkin/face_segmentation

**Comment by iperov** [comment]
@petergerten is this producing 68 landmarks?

**Comment by shaoanlu** [comment]
Although here is not a forum, everyone is welcome to post their thoughts and findings that can produce a positive progression of the project.

**Comment by mrgloom** [comment]
About the masks / semantic segmentation :

Seems this recent paper use segmentation masks:
https://nirkin.com/fsgan/

Also looks like some laarger dataset with masks is released:
https://github.com/switchablenorms/CelebAMask-HQ

**Comment by iperov** [comment]
my DeepFaceLab already has facesegmentation based on https://github.com/ternaus/TernausNet
