### ISSUE TITLE
Training speed?

### ISSUE THREAD

**Issue by Yare-zz** [shaoanlu/faceswap-GAN#66]
How long should it take to train 50 generations using the 128x128 notebook on an EC2 p2.xlarge instance?

1 NVIDIA K80 GPU
4 vCPUs
61 GiB RAM
EBS-optimized

My input images are 256x256. 
4,200 in set A
2,500 in set B

It took about 10 minutes to see the "working..." print. Is that right, or have I done something sub-optimal? Fallen back on software or created some other bottleneck?

Thanks.

**Comment by shaoanlu** [comment]
It seems like you are not using GPU for training. I have 1s/iter when training 64x64 models on K80. Take a look at #17 .

**Comment by ok-sweat** [comment]
> It seems like you are not using GPU for training. I have 1s/iter when training 64x64 models on K80. Take a look at #17 .

How to use GPU in this project?
