### ISSUE TITLE
The Mask geneartion and learn process

### ISSUE THREAD

**Issue by Nelthirion** [shaoanlu/faceswap-GAN#7]
I just saw the new update on mask generation and wanted to ask if you could elaborate on how it works and if the code is available to inspect...

By the way, nice idea (and implementation) !

**Comment by shaoanlu** [comment]
The read about masking on [CAGAN](https://arxiv.org/abs/1709.04695) paper.

Basically, you simply increase the output channel of generator from 3 (representing RGB) to 4 (representing alpha, RGB, denoted as `[y_alpha, y_rgb]`). Alpha channel (0 <= `alpha` <= 1) is treated as the segmentation mask, which we hope the model will learn.

The actual output image `masked_output` is a linear combination of input image (denoted `x_rgb`) and output RGB image `y_rgb`:
```python
 masked_output = y_alpha * y_rgb + (1 - y_alpha) * x_rgb
```

**Comment by deepfakes** [comment]
Hi @shaoanlu ,

I'm having a look at your code, and it's purely awesome! We are currently in the process of making the code base more flexible, and I hope we will be able to embed your improvments in the main project!

Keep up the good work!
