### ISSUE TITLE
The shape of face did't match, Using default setting.

### ISSUE THREAD

**Issue by isleon** [shaoanlu/faceswap-GAN#71]
[https://gfycat.com/RingedGranularBluefintuna](url)
I'm using FaceSwap_GAN_v2_train for the traing and creating video. Every setting is by default.
am I supposed to use larger img size? 
New to this, please help. thx

**Comment by shaoanlu** [comment]
Does the video result matches the previews during training? How many iterations did you train for?

**Comment by isleon** [comment]
The previews looks fine, I only got 600 pics (from one video) each face for the training. About 4k iterations and the size of chopped face imgs are 170x170 and 256x256 is that a problem?
Its the dataset too small to handle it? I've noticed that you can easy tell the face square because the brightness.
I'm training this in the Google Colaboratory. Only change the batch size to 128, it still takes me about one day for 4k iterations.

**Comment by shaoanlu** [comment]
Set batch size to 8 and train for 15~20k. I can’t see the benefit increasing batch size to 128 since the training samples are homogeneous.

**Comment by isleon** [comment]
thx for you patient, I will try this out.

**Comment by isleon** [comment]
Bytheway, the train speed is too slow, I checked this
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
and it shows 
```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 13883460739738187703
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 291504128
locality {
  bus_id: 1
}
incarnation: 5209474965337415910
physical_device_desc: "device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7"
]
```
it looks like GPU is available. but  
[13/150][150] Loss_DA: 0.168963 Loss_DB: 0.178503 Loss_GA: 0.273648 Loss_GB: 0.288085 time: 1251.794096

it takes me about 10m to see "working", I only installed the requirement listed, am I missing something?

**Comment by shaoanlu** [comment]
Batch size?

**Comment by isleon** [comment]
32

**Comment by shaoanlu** [comment]
I’m not sure why it took 10mins for displaying “working”. But it seems like it take 1200 sec for 150 iters, that is ~ 10 sec per iter, which is reasonable for bs 32. Notice that bs is proportional to training time **per iter**, so it takes 4x longer than bs 8.
