### ISSUE TITLE
Training iteration duration

### ISSUE THREAD

**Issue by visualmemories** [shaoanlu/faceswap-GAN#8]
How long should a single iteration take to train? For reference, I'm using a Tesla P100 and it's taking about 50 seconds.

**Comment by visualmemories** [comment]
Because of a configuration issue my GPU wasn't being used. For anyone reading, a single iteration should take ~1 second if not less.

**Comment by BillyHalley** [comment]
How did you solve this? I followed that link but I didn't manage to make it work on the GPU 
@visualmemories
