### ISSUE TITLE
always got error when `clip1.fl_image(process_video).subclip(1, 10)`

### ISSUE THREAD

**Issue by shadowwider** [shaoanlu/faceswap-GAN#80]
`<ipython-input-59-6112ca662e3a> in process_video(input_img)
    361 
    362         print(len(roi_image),type(roi_image))
--> 363         ae_input = cv2.resize(roi_image, (64,64))/255. * 2 - 1
    364         np.squeeze(np.array([path_abgr_A([[ae_input]])]))
    365         result, result_a, result_bgr = generate_face(ae_input, path_func, roi_size, roi_image)

error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize`
what cause this?

**Comment by shaoanlu** [comment]
Thanks for the feedback, this issue has been fixed.
