### ISSUE TITLE
FaceSwap_GAN_v2_train.ipynb   NotJsonError 

### ISSUE THREAD

**Issue by hengshanji** [shaoanlu/faceswap-GAN#81]
I want to train use FaceSwap_GAN_v2_train.ipynb. But when run jupyter notebook i get error like:
FaceSwap_GAN_v2_train.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c...',)

Is someone else meet this problem?

**Comment by shaoanlu** [comment]
Change `.astype("uint8")` to `.astype(np.uint8)`

**Comment by hengshanji** [comment]
Thank you very much !
