### ISSUE TITLE
Per-pixel means of VGG Face

### ISSUE THREAD

**Issue by xthan** [shaoanlu/faceswap-GAN#84]
Hi,
The RGB means used in this repo is different from the original vggface repo:
 
https://github.com/rcmalli/keras-vggface/blob/master/keras_vggface/utils.py#L49

Will this affect the results?

**Comment by shaoanlu** [comment]
I used ResNet50 in previous version and forgot to change the corresponding RGB means when switched to VGG16. I'll fix this, thanks!
